### ISSUE TITLE
Out of memory error when using related terms filter on a page with no related taxonomy terms

### ISSUE THREAD

**Issue by mwentz** [Jetski5822/Orchard.Taxonomies.ProjectionFilters#2]
Start with a blank site.
Create a taxonomy Foo with terms.
Create a query called "Related Items" with Related Taxonomy filter using Taxonomy: Foo
Add a projection widget on the homepage using the "Related Items" widget.
Error message: Exception of type 'System.OutOfMemoryException' was thrown.

Note: if the query has a Content Type filter set this error does not happen.

Error from the logs:

2015-02-26 12:02:43,080 [44] Orchard.Exceptions.DefaultExceptionPolicy - Default - An unexpected exception was caught
 http://localhost:30321/OrchardLocal/
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Text.StringBuilder.ToString()
   at System.IO.StringWriter.ToString()
   at Orchard.Mvc.Spooling.HtmlStringWriter.ToHtmlString() in c:\bitbucket\evt-orchard-taxaproto\src\Orchard\Mvc\Spooling\HtmlStringWriter.cs:line 18
   at System.Web.HttpUtility.HtmlEncode(Object value)
   at System.Web.WebPages.WebPageBase.Write(Object value)
   at CallSite.Target(Closure , CallSite , _Page_Core_Shapes_Views_Document_cshtml , Object )
   at ASP._Page_Core_Shapes_Views_Document_cshtml.Execute() in c:\bitbucket\evt-orchard-taxaproto\src\Orchard.Web\Core\Shapes\Views\Document.cshtml:line 21
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at System.Web.Mvc.RazorView.RenderView(ViewContext viewContext, TextWriter writer, Object instance)
   at System.Web.Mvc.BuildManagerCompiledView.Render(ViewContext viewContext, TextWriter writer)
   at System.Web.Mvc.HtmlHelper.RenderPartialInternal(String partialViewName, ViewDataDictionary viewData, Object model, TextWriter writer, ViewEngineCollection viewEngineCollection)
   at System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model, ViewDataDictionary viewData)
   at System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model)
   at Orchard.DisplayManagement.Descriptors.ShapeTemplateStrategy.ShapeTemplateBindingStrategy.Render(ShapeDescriptor shapeDescriptor, DisplayContext displayContext, HarvestShapeInfo harvestShapeInfo, HarvestShapeHit harvestShapeHit) in c:\bitbucket\evt-orchard-taxaproto\src\Orchard\DisplayManagement\Descriptors\ShapeTemplateStrategy\ShapeTemplateBindingStrategy.cs:line 151
   at Orchard.DisplayManagement.Descriptors.ShapeTemplateStrategy.ShapeTemplateBindingStrategy.<>c__DisplayClass26.<>c__DisplayClass28.<Discover>b__15(DisplayContext displayContext) in c:\bitbucket\evt-orchard-taxaproto\src\Orchard\DisplayManagement\Descriptors\ShapeTemplateStrategy\ShapeTemplateBindingStrategy.cs:line 133
   at Orchard.DisplayManagement.Descriptors.ShapeAlterationBuilder.<>c__DisplayClass3.<>c__DisplayClass5.<BoundAs>b__2(DisplayContext displayContext) in c:\bitbucket\evt-orchard-taxaproto\src\Orchard\DisplayManagement\Descriptors\ShapeAlterationBuilder.cs:line 56
   at Orchard.DisplayManagement.Implementation.DefaultDisplayManager.Process(ShapeBinding shapeBinding, IShape shape, DisplayContext context) in c:\bitbucket\evt-orchard-taxaproto\src\Orchard\DisplayManagement\Implementation\DefaultDisplayManager.cs:line 185
   at Orchard.DisplayManagement.Implementation.DefaultDisplayManager.Execute(DisplayContext context) in c:\bitbucket\evt-orchard-taxaproto\src\Orchard\DisplayManagement\Implementation\DefaultDisplayManager.cs:line 104
   at Orchard.DisplayManagement.Implementation.DisplayHelper.ShapeExecute(Object shape) in c:\bitbucket\evt-orchard-taxaproto\src\Orchard\DisplayManagement\Implementation\DisplayHelper.cs:line 86
   at Orchard.DisplayManagement.Implementation.DisplayHelper.Invoke(String name, INamedEnumerable`1 parameters) in c:\bitbucket\evt-orchard-taxaproto\src\Orchard\DisplayManagement\Implementation\DisplayHelper.cs:line 44
   at Orchard.DisplayManagement.Implementation.DisplayHelper.TryInvoke(InvokeBinder binder, Object[] args, Object& result) in c:\bitbucket\evt-orchard-taxaproto\src\Orchard\DisplayManagement\Implementation\DisplayHelper.cs:line 29
   at CallSite.Target(Closure , CallSite , Object , Object )
   at Orchard.Mvc.ViewEngines.ThemeAwareness.LayoutAwareViewEngine.<>c__DisplayClass7.<FindView>b__5(ViewContext viewContext, TextWriter writer, IViewDataContainer viewDataContainer) in c:\bitbucket\evt-orchard-taxaproto\src\Orchard\Mvc\ViewEngines\ThemeAwareness\LayoutAwareViewEngine.cs:line 63
   at Orchard.Mvc.ViewEngines.ThemeAwareness.LayoutAwareViewEngine.LayoutView.Render(ViewContext viewContext, TextWriter writer) in c:\bitbucket\evt-orchard-taxaproto\src\Orchard\Mvc\ViewEngines\ThemeAwareness\LayoutAwareViewEngine.cs:line 90
   at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResult(ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)

**Comment by mwentz** [comment]
Sorry never mind, this was a result of having Shape Tracing on. I also realized that if anything this would be a bug with the projections module and not the filter.
